export const SIGNIN_BEGIN_EVENT = 'SIGNIN_BEGIN';
export const SIGNIN_SUCCESS_EVENT = 'SIGNIN_SUCCESS';

export const SIGNOUT_BEGIN_EVENT = 'SIGNOUT_BEGIN';
export const SIGNOUT_SUCCESS_EVENT = 'SIGNOUT_SUCCESS';
